### ISSUE TITLE
vagrant up not working

### ISSUE THREAD

**Issue by danielrona** [grschafer/dota2rails-deploy#1]
Hi there,
trying to get this running and I get the following error after downloading the repo and it's modules.

```
daniel@replayparser:~/dota2rails-deploy$ vagrant up --no-provision
/home/daniel/dota2rails-deploy/Vagrantfile:7:in `<top (required)>': undefined method `configure' for Vagrant:Module (NoMethodError)
        from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:115:in `load'
        from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:115:in `block in procs_for_source'
        from /usr/lib/ruby/vendor_ruby/vagrant/config.rb:41:in `block in capture_configures'
        from <internal:prelude>:10:in `synchronize'
        from /usr/lib/ruby/vendor_ruby/vagrant/config.rb:36:in `capture_configures'
        from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:114:in `procs_for_source'
        from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:51:in `block in set'
        from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:45:in `each'
        from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:45:in `set'
        from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:377:in `block in load_config!'
        from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:392:in `call'
        from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:392:in `load_config!'
        from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:327:in `load!'
        from /usr/bin/vagrant:40:in `<main>'
```

Any idea what I'm doing wrong?

**Comment by grschafer** [comment]
Heya, sorry for the slow response. Unfortunately, I won't be able to look into this for another couple days.

In the meantime, if you're after something specific I can probably point you to where it is in the code. If you're interested in the parsing side of it, note that [skadi/tarrasque](https://github.com/skadistats) (which I used for this) are deprecated and this repo hasn't been updated in a long time, so I'm not sure that it would work on current replays.
